name: 'dbt_robust_testing'
version: '1.0.0'

profile: 'dbt_robust_testing'

analysis-paths: ["src/analyses"]
model-paths: ["src/models"]
seed-paths: ["src/seeds"]
macro-paths: ["src/macros"]
test-paths: ["src/tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_robust_testing:
    materialized: table

vars:
  test_from_sample: true